//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVSİTESİ.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEğitimlerim
    {
        public int ID { get; set; }
        public string Başlık { get; set; }
        public string AltBaşlık1 { get; set; }
        public string AltBaşlık2 { get; set; }
        public string GNO { get; set; }
        public string Tarih { get; set; }
    }
}
